set(_AMENT_PACKAGE_NAME "integ_command")
set(integ_command_VERSION "0.0.0")
set(integ_command_MAINTAINER "Thibault <tl.leblanc@outlook.fr>")
set(integ_command_BUILD_DEPENDS "rclcpp" "sensor_msgs" "pcl_ros" "pcl_conversions" "std_msgs" "Eigen")
set(integ_command_BUILDTOOL_DEPENDS "ament_cmake")
set(integ_command_BUILD_EXPORT_DEPENDS "rclcpp" "sensor_msgs" "pcl_ros" "pcl_conversions" "std_msgs" "Eigen")
set(integ_command_BUILDTOOL_EXPORT_DEPENDS )
set(integ_command_EXEC_DEPENDS "rclcpp" "sensor_msgs" "pcl_ros" "pcl_conversions" "std_msgs" "Eigen")
set(integ_command_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(integ_command_GROUP_DEPENDS )
set(integ_command_MEMBER_OF_GROUPS )
set(integ_command_DEPRECATED "")
set(integ_command_EXPORT_TAGS)
list(APPEND integ_command_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
