set(_AMENT_PACKAGE_NAME "blue_detection")
set(blue_detection_VERSION "0.0.0")
set(blue_detection_MAINTAINER "renato <renato.ramos@poli.ufrj.bf>")
set(blue_detection_BUILD_DEPENDS )
set(blue_detection_BUILDTOOL_DEPENDS "ament_cmake")
set(blue_detection_BUILD_EXPORT_DEPENDS )
set(blue_detection_BUILDTOOL_EXPORT_DEPENDS )
set(blue_detection_EXEC_DEPENDS "rclpy" "sensor_msgs")
set(blue_detection_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(blue_detection_GROUP_DEPENDS )
set(blue_detection_MEMBER_OF_GROUPS )
set(blue_detection_DEPRECATED "")
set(blue_detection_EXPORT_TAGS)
list(APPEND blue_detection_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
