#!/usr/bin/env python

import rospy
from sensor_msgs.msg import JointState
from gkd_models.srv import *

def test_callback():
	S = JointState()
	S.name.append('fake_joint1')
	S.position.append(2)
	S.velocity.append(1)
	S.name.append('fake_joint2')
	S.position.append(2)
	S.velocity.append(1)
	S.effort.append(0.1)
	S.effort.append(0)

	rospy.wait_for_service('Dynamic')
	dyna = rospy.ServiceProxy('Dynamic', Dynamic)

	try:
		resp = dyna(S)
		print(resp)
	except rospy.ServiceException as exc:
		print("Service did not process request: " + str(exc))


if __name__ == '__main__':
    try:
        test_callback()
    except rospy.ROSInterruptException:
        pass
