#!/usr/bin/env python

import rospy
from sensor_msgs.msg import JointState
from gkd_models.srv import *

def test_callback():
	pos=[0.2,0.1]
	elbow=True

	rospy.wait_for_service('MGI')
	q = rospy.ServiceProxy('MGI', MGI)

	try:
		resp = q(pos,elbow)
		print(resp)
	except rospy.ServiceException as exc:
		print("Service did not process request: " + str(exc))


if __name__ == '__main__':
    try:
        test_callback()
    except rospy.ROSInterruptException:
        pass
