set(_AMENT_PACKAGE_NAME "visual_servoing")
set(visual_servoing_VERSION "0.0.0")
set(visual_servoing_MAINTAINER "t-lemmel <lemmeltom@gmail.com>")
set(visual_servoing_BUILD_DEPENDS "rclpy" "integ_msgs" "std_msgs")
set(visual_servoing_BUILDTOOL_DEPENDS "ament_cmake")
set(visual_servoing_BUILD_EXPORT_DEPENDS "rclpy" "integ_msgs" "std_msgs")
set(visual_servoing_BUILDTOOL_EXPORT_DEPENDS )
set(visual_servoing_EXEC_DEPENDS "rclpy" "integ_msgs" "std_msgs")
set(visual_servoing_TEST_DEPENDS )
set(visual_servoing_GROUP_DEPENDS )
set(visual_servoing_MEMBER_OF_GROUPS )
set(visual_servoing_DEPRECATED "")
set(visual_servoing_EXPORT_TAGS)
list(APPEND visual_servoing_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
