set(_AMENT_PACKAGE_NAME "integ_description")
set(integ_description_VERSION "1.0.0")
set(integ_description_MAINTAINER " <TODO@email.com>")
set(integ_description_BUILD_DEPENDS )
set(integ_description_BUILDTOOL_DEPENDS "ament_cmake")
set(integ_description_BUILD_EXPORT_DEPENDS )
set(integ_description_BUILDTOOL_EXPORT_DEPENDS )
set(integ_description_EXEC_DEPENDS )
set(integ_description_TEST_DEPENDS )
set(integ_description_GROUP_DEPENDS )
set(integ_description_MEMBER_OF_GROUPS )
set(integ_description_DEPRECATED "")
set(integ_description_EXPORT_TAGS)
list(APPEND integ_description_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
